import type { Metadata } from 'next'
import './globals.css'
import { ReactNode } from 'react'
import Tab from './Tab'
import openSans from '@/fonts/openSans'
import Link from 'next/link'
import Nav from './Nav'

export const metadata: Metadata = {
  title: 'Orlando Silva',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode}) {
  return (
    <html lang="en">
      <body className={`w-screen relative flex flex-col ${openSans.light}`}>
        <div className='w-full h-[120px] flex items-center justify-between px-[60px]'>
          <Link href="/" >
            <button className='w-fit text-4xl font-medium tracking-wide text-gray-900'>Orlando Silva</button>
          </Link>
          <Nav />
        </div>
        {children}
      </body>
    </html>
  )
}
